#Config Iniciales
spring.application.name=sistemacontrolventas

#Config DB
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

#Config Security
spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASSWORD}