#Config Iniciales
spring.application.name=SistemaControlVentas

#Config DB
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}
spring.jpa.hibernate.ddl-auto=update